import React from 'react'

const iconMapping = {
  'clear sky': ['http://openweathermap.org/img/wn/01d@2x.png', 'http://openweathermap.org/img/wn/01n@2x.png'],
  'few clouds': ['http://openweathermap.org/img/wn/02d@2x.png', 'http://openweathermap.org/img/wn/02n@2x.png'],
  'scattered clouds': ['http://openweathermap.org/img/wn/03d@2x.png', 'http://openweathermap.org/img/wn/03n@2x.png'],
  'broken clouds': ['http://openweathermap.org/img/wn/04d@2x.png', 'http://openweathermap.org/img/wn/04n@2x.png'],
  'overcast clouds': ['http://openweathermap.org/img/wn/04d@2x.png', 'http://openweathermap.org/img/wn/04n@2x.png'],
  'light intensity drizzle': ['http://openweathermap.org/img/wn/09d@2x.png', 'http://openweathermap.org/img/wn/09n@2x.png'],
  'drizzle': ['http://openweathermap.org/img/wn/09d@2x.png', 'http://openweathermap.org/img/wn/09n@2x.png'],
  'heavy intensity drizzle': ['http://openweathermap.org/img/wn/09d@2x.png', 'http://openweathermap.org/img/wn/09n@2x.png'],
  'light intensity drizzle rain': ['http://openweathermap.org/img/wn/09d@2x.png', 'http://openweathermap.org/img/wn/09n@2x.png'],
  'drizzle rain': ['http://openweathermap.org/img/wn/09d@2x.png', 'http://openweathermap.org/img/wn/09n@2x.png'],
  'heavy intensity drizzle rain': ['http://openweathermap.org/img/wn/09d@2x.png', 'http://openweathermap.org/img/wn/09n@2x.png'],
  'shower rain and drizzle': ['http://openweathermap.org/img/wn/09d@2x.png', 'http://openweathermap.org/img/wn/09n@2x.png'],
  'heavy shower rain and drizzle': ['http://openweathermap.org/img/wn/09d@2x.png', 'http://openweathermap.org/img/wn/09n@2x.png'],
  'shower drizzle': ['http://openweathermap.org/img/wn/09d@2x.png', 'http://openweathermap.org/img/wn/09n@2x.png'],
  'light intensity shower rain': ['http://openweathermap.org/img/wn/09d@2x.png', 'http://openweathermap.org/img/wn/09n@2x.png'],
  'shower rain': ['http://openweathermap.org/img/wn/09d@2x.png', 'http://openweathermap.org/img/wn/09n@2x.png'],
  'heavy intensity shower rain': ['http://openweathermap.org/img/wn/09d@2x.png', 'http://openweathermap.org/img/wn/09n@2x.png'],
  'ragged shower rain': ['http://openweathermap.org/img/wn/09d@2x.png', 'http://openweathermap.org/img/wn/09n@2x.png'],
  'light rain': ['http://openweathermap.org/img/wn/10d@2x.png', 'http://openweathermap.org/img/wn/10n@2x.png'],
  'moderate rain': ['http://openweathermap.org/img/wn/10d@2x.png', 'http://openweathermap.org/img/wn/10n@2x.png'],
  'heavy intensity rain': ['http://openweathermap.org/img/wn/10d@2x.png', 'http://openweathermap.org/img/wn/10n@2x.png'],
  'very heavy rain': ['http://openweathermap.org/img/wn/10d@2x.png', 'http://openweathermap.org/img/wn/10n@2x.png'],
  'extreme rain': ['http://openweathermap.org/img/wn/10d@2x.png', 'http://openweathermap.org/img/wn/10n@2x.png'],
  'rain': ['http://openweathermap.org/img/wn/10d@2x.png', 'http://openweathermap.org/img/wn/10n@2x.png'],
  'thunderstorm with light rain': ['http://openweathermap.org/img/wn/11d@2x.png', 'http://openweathermap.org/img/wn/11n@2x.png'],
  'thunderstorm with rain': ['http://openweathermap.org/img/wn/11d@2x.png', 'http://openweathermap.org/img/wn/11n@2x.png'],
  'thunderstorm with heavy rain': ['http://openweathermap.org/img/wn/11d@2x.png', 'http://openweathermap.org/img/wn/11n@2x.png'],
  'light thunderstorm': ['http://openweathermap.org/img/wn/11d@2x.png', 'http://openweathermap.org/img/wn/11n@2x.png'],
  'thunderstorm': ['http://openweathermap.org/img/wn/11d@2x.png', 'http://openweathermap.org/img/wn/11n@2x.png'],
  'heavy thunderstorm': ['http://openweathermap.org/img/wn/11d@2x.png', 'http://openweathermap.org/img/wn/11n@2x.png'],
  'ragged thunderstorm': ['http://openweathermap.org/img/wn/11d@2x.png', 'http://openweathermap.org/img/wn/11n@2x.png'],
  'thunderstorm with light drizzle': ['http://openweathermap.org/img/wn/11d@2x.png', 'http://openweathermap.org/img/wn/11n@2x.png'],
  'thunderstorm with drizzle': ['http://openweathermap.org/img/wn/11d@2x.png', 'http://openweathermap.org/img/wn/11n@2x.png'],
  'thunderstorm with heavy drizzle': ['http://openweathermap.org/img/wn/11d@2x.png', 'http://openweathermap.org/img/wn/11n@2x.png'],
  'freezing rain': ['http://openweathermap.org/img/wn/13d@2x.png', 'http://openweathermap.org/img/wn/13n@2x.png'],
  'light snow': ['http://openweathermap.org/img/wn/13d@2x.png', 'http://openweathermap.org/img/wn/13n@2x.png'],
  'snow': ['http://openweathermap.org/img/wn/13d@2x.png', 'http://openweathermap.org/img/wn/13n@2x.png'],
  'heavy snow': ['http://openweathermap.org/img/wn/13d@2x.png', 'http://openweathermap.org/img/wn/13n@2x.png'],
  'sleet': ['http://openweathermap.org/img/wn/13d@2x.png', 'http://openweathermap.org/img/wn/13n@2x.png'],
  'light shower sleet': ['http://openweathermap.org/img/wn/13d@2x.png', 'http://openweathermap.org/img/wn/13n@2x.png'],
  'shower sleet': ['http://openweathermap.org/img/wn/13d@2x.png', 'http://openweathermap.org/img/wn/13n@2x.png'],
  'light rain and snow': ['http://openweathermap.org/img/wn/13d@2x.png', 'http://openweathermap.org/img/wn/13n@2x.png'],
  'rain and snow': ['http://openweathermap.org/img/wn/13d@2x.png', 'http://openweathermap.org/img/wn/13n@2x.png'],
  'light shower snow': ['http://openweathermap.org/img/wn/13d@2x.png', 'http://openweathermap.org/img/wn/13n@2x.png'],
  'shower snow': ['http://openweathermap.org/img/wn/13d@2x.png', 'http://openweathermap.org/img/wn/13n@2x.png'],
  'heavy shower snow': ['http://openweathermap.org/img/wn/13d@2x.png', 'http://openweathermap.org/img/wn/13n@2x.png'],
  'mist': ['http://openweathermap.org/img/wn/50d@2x.png', 'http://openweathermap.org/img/wn/50n@2x.png'],
  'smoke': ['http://openweathermap.org/img/wn/50d@2x.png', 'http://openweathermap.org/img/wn/50n@2x.png'],
  'haze': ['http://openweathermap.org/img/wn/50d@2x.png', 'http://openweathermap.org/img/wn/50n@2x.png'],
  'sand/dust whirls': ['http://openweathermap.org/img/wn/50d@2x.png', 'http://openweathermap.org/img/wn/50n@2x.png'],
  'fog': ['http://openweathermap.org/img/wn/50d@2x.png', 'http://openweathermap.org/img/wn/50n@2x.png'],
  'sand': ['http://openweathermap.org/img/wn/50d@2x.png', 'http://openweathermap.org/img/wn/50n@2x.png'],
  'dust': ['http://openweathermap.org/img/wn/50d@2x.png', 'http://openweathermap.org/img/wn/50n@2x.png'],
  'volcanic ash': ['http://openweathermap.org/img/wn/50d@2x.png', 'http://openweathermap.org/img/wn/50n@2x.png'],
  'squalls': ['http://openweathermap.org/img/wn/50d@2x.png', 'http://openweathermap.org/img/wn/50n@2x.png'],
  'tornado': ['http://openweathermap.org/img/wn/50d@2x.png', 'http://openweathermap.org/img/wn/50n@2x.png']
}

export default iconMapping